"use client";

import { useState } from "react";
import { ThemeControl } from "../theme-control";
import "./page.css";

const VOCABULARY_BY_LEVEL = { A1: 800, A2: 1800, B1: 3500, B2: 5500, C1: 7800, C2: 10500 };

function readLearningState() {
  try { return JSON.parse(sessionStorage.getItem("inread-state") || "null"); } catch { return null; }
}

function buildPlanState(result) {
  const state = readLearningState();
  const book = state?.selectedBook;
  const level = String(result.cefr_level || "").toUpperCase();
  const estimatedVocab = VOCABULARY_BY_LEVEL[level];
  if (!book || !Array.isArray(book.vocabulary) || !book.vocabulary.length || !estimatedVocab) return null;
  const required = Number(book.recommendedRange?.[0]) || estimatedVocab;
  const gap = Math.max(0, required - estimatedVocab);
  const wordCount = Math.max(8, Math.min(book.vocabulary.length, 8 + Math.ceil(gap / 180)));
  const words = [...book.vocabulary]
    .sort((a, b) => a.chapter - b.chapter || b.frequency - a.frequency || a.difficulty - b.difficulty)
    .slice(0, wordCount);
  const tierKey = words.length <= 1 ? "ready_now" : words.length <= 4 ? "good_to_go" : words.length <= 8 ? "can_try" : words.length <= 12 ? "stretch" : words.length <= 18 ? "challenging" : "not_recommended";
  const completedAt = new Date().toISOString();
  return {
    ...state,
    readerProfile: { estimatedVocab, level, sourceBook: `CEFR ${level}`, sourceLevel: level, unknownCount: null, assessment: { type: `cefr-${level}`, score: level, source: "cefr-tool", completedAt } },
    unknownWords: words,
    result: { unknownCount: words.length, level: words.length <= 5 ? "L1" : words.length <= 20 ? "L2" : "L3", tierKey },
    plan: [], completion: [], studySession: null, wordRecords: {}, planProgress: {}, trainingDay: 0,
    gateUnlocked: false, directChallenge: false,
    readerAccess: { source: "cefr-tool", matchKey: gap > 1300 ? "not_yet" : gap > 500 ? "demanding" : gap > 0 ? "stretch" : "recommended" },
    vocabularyPlanSource: "cefr-tool", cefrAssessment: { ...result, completedAt }
  };
}

function downloadResult(result) {
  const canvas = document.createElement("canvas");
  canvas.width = 1600; canvas.height = 1050;
  const context = canvas.getContext("2d");
  const background = context.createLinearGradient(0, 0, canvas.width, canvas.height);
  background.addColorStop(0, "#f9ddc9"); background.addColorStop(.5, "#f7f4ee"); background.addColorStop(1, "#d6e7e1");
  context.fillStyle = background; context.fillRect(0, 0, canvas.width, canvas.height);
  context.fillStyle = "rgba(255,255,255,.86)"; context.roundRect(72, 72, 1456, 906, 42); context.fill();
  context.fillStyle = "#1d2a32"; context.font = "bold 58px Georgia, serif"; context.fillText("InRead CEFR Assessment", 138, 172);
  context.fillStyle = "#bc5f3c"; context.fillRect(138, 196, 190, 8);
  const lines = [
    [`评测等级：${result.cefr_level} (${result.cefr_band || ""})`, "bold 44px Georgia, serif", "#29775d"],
    [`能力估计：${result.ability_estimate || "-"}    置信度：${result.confidence || "-"}`, "30px Georgia, serif", "#1d2a32"],
    [`答题数：${result.questions_answered || "-"}    耗时：${result.minutes_used || "-"} 分钟`, "30px Georgia, serif", "#1d2a32"],
    [`优势：${(result.strengths || []).join("；") || "-"}`, "30px Georgia, serif", "#1d2a32"],
    [`建议加强：${(result.gaps || []).join("；") || "-"}`, "30px Georgia, serif", "#1d2a32"],
    [`总结：${result.llm_summary || "-"}`, "30px Georgia, serif", "#1d2a32"]
  ];
  let y = 286;
  for (const [text, font, color] of lines) {
    context.font = font; context.fillStyle = color;
    const words = String(text).split(/\s+/); let line = "";
    for (const word of words) {
      const next = line ? `${line} ${word}` : word;
      if (context.measureText(next).width > 1240 && line) { context.fillText(line, 138, y); y += 46; line = word; } else line = next;
    }
    if (line) context.fillText(line, 138, y);
    y += 66;
  }
  context.fillStyle = "#60727d"; context.font = "24px Georgia, serif";
  context.fillText(`Generated by InRead · ${new Date().toLocaleString()}`, 138, 925);
  const link = document.createElement("a");
  link.download = `InRead-CEFR-${result.cefr_level || "result"}.png`; link.href = canvas.toDataURL("image/png"); link.click();
}

export default function CefrPage() {
  const [payload, setPayload] = useState(null);
  const [choice, setChoice] = useState(null);
  const [status, setStatus] = useState("");
  const [loading, setLoading] = useState(false);

  async function start() {
    setLoading(true); setStatus("正在初始化测试...");
    try {
      const response = await fetch("/api/cefr/start", { method: "POST" });
      const next = await response.json();
      if (!response.ok || !next.session_id) throw new Error(next.error || "测试服务暂时不可用。");
      setPayload(next); setChoice(null); setStatus("");
    } catch (error) { setStatus(error.message || "无法启动测试，请稍后重试。"); } finally { setLoading(false); }
  }

  async function submit(event) {
    event.preventDefault();
    if (choice === null || !payload) return setStatus("请先选择一个答案。");
    setLoading(true); setStatus("正在记录答案...");
    try {
      const response = await fetch("/api/cefr/answer", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ session_id: payload.session_id, choice_index: choice }) });
      const next = await response.json();
      if (!response.ok) throw new Error(next.error || "答案提交失败。");
      setPayload(next); setChoice(null); setStatus("");
    } catch (error) { setStatus(error.message || "答案提交失败，请重试。"); } finally { setLoading(false); }
  }

  async function importResult() {
    if (!payload?.session_id) return;
    setLoading(true); setStatus("正在导入 CEFR 成绩...");
    try {
      const response = await fetch("/api/cefr/import", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ session_id: payload.session_id }) });
      const body = await response.json();
      if (!response.ok) throw new Error(body.error || "导入失败。");
      const state = buildPlanState(body.result);
      if (!state) { location.assign("/legacy/library.html?assessment=cefr"); return; }
      sessionStorage.setItem("inread-state", JSON.stringify(state));
      const profileResponse = await fetch("/api/profile", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ learningState: state }) });
      if (!profileResponse.ok) throw new Error("成绩已导入，但同步学习计划失败，请重试。");
      location.assign("/legacy/plan.html");
    } catch (error) { setStatus(error.message || "导入失败，请稍后重试。"); setLoading(false); }
  }

  if (payload?.status === "finished") {
    const result = payload.result;
    return <main className="cefr-page"><header className="cefr-nav"><a href="/legacy/assessment.html">InRead</a><ThemeControl /></header><section className="cefr-card cefr-result"><span>INREAD CEFR</span><h1>评测完成：{result.cefr_level}</h1><p>{result.llm_summary}</p><div className="cefr-grid"><b>能力估计：{result.ability_estimate}</b><b>置信度：{result.confidence}</b><b>答题数：{result.questions_answered}</b><b>耗时：{result.minutes_used} 分钟</b></div><div className="cefr-actions"><button className="secondary" onClick={() => downloadResult(result)}>下载完整结果图片</button><button onClick={importResult} disabled={loading}>{loading ? "正在导入..." : "导入成绩并继续 InRead"}</button><button className="quiet" onClick={() => location.assign("/legacy/library.html")}>暂不导入，返回图书库</button></div><p className="cefr-status" aria-live="polite">{status}</p></section></main>;
  }
  const question = payload?.question;
  return <main className="cefr-page"><header className="cefr-nav"><a href="/legacy/assessment.html">InRead</a><ThemeControl /></header><section className="cefr-card"><span>INREAD CEFR</span><h1>20 分钟自适应 CEFR 英语测试</h1><p>每 3 题根据你的表现调整难度。完成后可下载报告，并把结果导入当前 InRead 账户。</p>{!question ? <button onClick={start} disabled={loading}>{loading ? "正在启动..." : "开始测试"}</button> : <form onSubmit={submit}><div className="cefr-meta">已答 {payload.progress.answered} / {payload.progress.total_questions} · 当前等级 {payload.progress.estimated_band}</div><h2>{question.question}</h2>{question.passage && <p className="cefr-passage">{question.passage}</p>}<div className="cefr-options">{question.options.map((option, index) => <label className={choice === index ? "selected" : ""} key={`${index}-${option}`}><input type="radio" name="cefr-answer" checked={choice === index} onChange={() => setChoice(index)} />{option}</label>)}</div><button disabled={loading}>{loading ? "提交中..." : "提交并继续"}</button></form>}<p className="cefr-status" aria-live="polite">{status}</p></section></main>;
}
