import { NextResponse } from "next/server";
import { currentUser } from "../../../lib/auth";

export const runtime = "nodejs";

const CEFR_ORIGIN = process.env.CEFR_SERVICE_ORIGIN || "http://127.0.0.1:17860";

function bridgeScript() {
  return `
<style>
  .inread-result-actions { margin-top: 22px; display: flex; gap: 10px; flex-wrap: wrap; }
  .inread-result-actions button { background: #355567; }
  .inread-result-actions .inread-import { background: #29775d; }
  .inread-import-status { width: 100%; color: #60727d; min-height: 20px; }
</style>
<script>
(() => {
  function resultLines(result) {
    return [
      "InRead CEFR Adaptive Assessment",
      "Estimated CEFR level: " + result.cefr_level + " (" + result.cefr_band + ")",
      "Ability estimate: " + result.ability_estimate + "    Confidence: " + result.confidence,
      "Questions answered: " + result.questions_answered + "    Time used: " + result.minutes_used + " minutes",
      "Strengths: " + (result.strengths || []).join("; "),
      "Needs work: " + (result.gaps || []).join("; "),
      "Summary: " + (result.llm_summary || "")
    ];
  }

  function wrapCanvasText(context, text, maxWidth) {
    const words = String(text).split(/\\s+/);
    const lines = [];
    let line = "";
    words.forEach((word) => {
      const next = line ? line + " " + word : word;
      if (context.measureText(next).width > maxWidth && line) {
        lines.push(line);
        line = word;
      } else {
        line = next;
      }
    });
    if (line) lines.push(line);
    return lines;
  }

  function downloadResult(result) {
    const canvas = document.createElement("canvas");
    canvas.width = 1600;
    canvas.height = 1120;
    const context = canvas.getContext("2d");
    const gradient = context.createLinearGradient(0, 0, canvas.width, canvas.height);
    gradient.addColorStop(0, "#f9ddc9");
    gradient.addColorStop(0.52, "#f7f4ee");
    gradient.addColorStop(1, "#d6e7e1");
    context.fillStyle = gradient;
    context.fillRect(0, 0, canvas.width, canvas.height);
    context.fillStyle = "rgba(255,255,255,.88)";
    context.roundRect(72, 72, 1456, 976, 42);
    context.fill();
    context.fillStyle = "#1d2a32";
    context.font = "bold 58px Georgia, serif";
    context.fillText("InRead CEFR Assessment", 138, 170);
    context.fillStyle = "#bc5f3c";
    context.fillRect(138, 195, 190, 8);
    let y = 286;
    resultLines(result).forEach((item, index) => {
      context.fillStyle = index === 1 ? "#29775d" : "#1d2a32";
      context.font = index === 1 ? "bold 43px Georgia, serif" : "30px Georgia, 'Noto Serif SC', serif";
      wrapCanvasText(context, item, 1260).forEach((line) => {
        context.fillText(line, 138, y);
        y += index === 1 ? 58 : 45;
      });
      y += 18;
    });
    context.fillStyle = "#60727d";
    context.font = "24px Georgia, serif";
    context.fillText("Generated by InRead · " + new Date().toLocaleString(), 138, 990);
    const link = document.createElement("a");
    link.download = "InRead-CEFR-" + result.cefr_level + ".png";
    link.href = canvas.toDataURL("image/png");
    link.click();
  }

  function addResultActions() {
    const payload = window.__inreadCefrResult;
    const resultSection = document.getElementById("result");
    if (!payload || !resultSection || resultSection.dataset.inreadActions || resultSection.style.display !== "block") return;
    resultSection.dataset.inreadActions = "true";
    const actions = document.createElement("div");
    actions.className = "inread-result-actions";
    actions.innerHTML = '<button type="button" class="inread-download">下载完整结果图片</button><button type="button" class="inread-import">导入成绩并返回 InRead</button><button type="button" class="inread-exit">不导入，返回 InRead</button><span class="inread-import-status" aria-live="polite"></span>';
    resultSection.appendChild(actions);
    const status = actions.querySelector(".inread-import-status");
    actions.querySelector(".inread-download").addEventListener("click", () => downloadResult(payload.result));
    actions.querySelector(".inread-exit").addEventListener("click", () => window.location.assign("/legacy/library.html"));
    actions.querySelector(".inread-import").addEventListener("click", async (event) => {
      event.currentTarget.disabled = true;
      status.textContent = "正在验证并导入 CEFR 成绩...";
      try {
        const response = await fetch("/api/cefr/import", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ session_id: payload.session_id })
        });
        const body = await response.json();
        if (!response.ok) throw new Error(body.error || "导入失败");
        status.textContent = "成绩已导入，正在返回 InRead...";
        window.location.assign("/legacy/library.html?assessment=cefr");
      } catch (error) {
        status.textContent = error.message || "导入失败，请稍后重试。";
        event.currentTarget.disabled = false;
      }
    });
  }

  const observer = new MutationObserver(addResultActions);
  observer.observe(document.documentElement, { childList: true, subtree: true, attributes: true, attributeFilter: ["style"] });
  addResultActions();
})();
</script>`;
}

export async function GET(request) {
  const user = await currentUser(request);
  if (!user) return NextResponse.json({ error: "UNAUTHORIZED" }, { status: 401 });
  try {
    const response = await fetch(`${CEFR_ORIGIN}/`, { cache: "no-store" });
    if (!response.ok) throw new Error(`CEFR service returned ${response.status}`);
    let html = await response.text();
    html = html
      .replace('fetch("/api/start"', 'fetch("/api/cefr/start"')
      .replace('fetch("/api/answer"', 'fetch("/api/cefr/answer"')
      .replace("function renderResult(payload) {", "function renderResult(payload) {\\n      window.__inreadCefrResult = payload;")
      .replace("</body>", `${bridgeScript()}</body>`);
    return new NextResponse(html, {
      headers: { "content-type": "text/html; charset=utf-8", "cache-control": "no-store" }
    });
  } catch {
    return NextResponse.json({ error: "CEFR_SERVICE_UNAVAILABLE" }, { status: 503 });
  }
}
